# [START appengine_websockets_yaml]
runtime: nodejs16
service: default

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

handlers:
  - url: /sm-ferring/static
    static_dir: build/sm-ferring/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/ui-lib-c2c-testing-3/index.html
    upload: build/ui-lib-c2c-testing-3/index.html
