trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Solvers Subscription(cc155193-80f2-4c4a-8e52-e81106774bf2)'
    appType: 'webAppContainer'
    WebAppName: 'msteamsvoice'
    deployToSlotOrASE: true
    ResourceGroupName: 'rg-eastus2-metadoctors'
    SlotName: 'production'
    DockerNamespace: 'msteamsvoice-adhna8b5fqfzbhac.canadacentral-01.azurewebsites.net'
    DockerRepository: 'containermstemasvoice.azurecr.io/teams-appmsteamsvoice'