name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read

    name: Deploy Front      
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: NPM Install
      run: npm install

    - name: Build the app
      run: npm run build --if-present

    - name: Archive production artifacts
      run: zip -r msteamsvoiceapp - Zip Deploy.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: msteamsvoiceapp - Zip Deploy
        path: msteamsvoiceapp - Zip Deploy.zip

    - name: Deploy to Azure Web App using Run From Package
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'msteamsvoiceapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: msteamsvoiceapp - Zip Deploy.zip